demo_test_product:
    resource: "@DemoTestBundle/Resources/config/routing/product.yml"
    prefix:   /product
    
weather_check:
    path:     /weather
    defaults: { _controller: DemoTestBundle:Default:weather }
demo_test_homepage:
    path:     /home
    defaults: { _controller: DemoTestBundle:Default:index }
    
demo_test_accueil:
    path:     /
    defaults: { _controller: DemoTestBundle:Default:home }

ville_new:
    path:     /new
    defaults: { _controller: "DemoTestBundle:Default:new" }
    methods:  [GET, POST]

demo_test_pays:
        resource: "@DemoTestBundle/Resources/config/routing/pays.yml"
        prefix:   /pays



