demo_test_product:
    resource: "@DemoTestBundle/Resources/config/routing/product.yml"
    prefix:   /product

demo_test_homepage:
    path:     /home
    defaults: { _controller: DemoTestBundle:Default:index }
    
demo_test_accueil:
    path:     /
    defaults: { _controller: DemoTestBundle:Default:home }
